-- MySQL Script generated by MySQL Workbench
-- Mon Oct 15 19:00:30 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`authors` (
  `author_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `author_name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`author_id`),
  UNIQUE INDEX `author_id_UNIQUE` (`author_id` ASC),
  UNIQUE INDEX `author_name_UNIQUE` (`author_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`images` (
  `image_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `image_alt` VARCHAR(64) NOT NULL,
  `image_filename` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`image_id`),
  UNIQUE INDEX `image_id_UNIQUE` (`image_id` ASC),
  UNIQUE INDEX `image_filename_UNIQUE` (`image_filename` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`songs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`songs` (
  `song_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `song_name` VARCHAR(128) NOT NULL,
  `song_author` BIGINT(20) UNSIGNED NOT NULL,
  `song_create_time` DATETIME NOT NULL,
  `song_filename` VARCHAR(60) NOT NULL,
  `song_image_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`song_id`),
  UNIQUE INDEX `song_id_UNIQUE` (`song_id` ASC),
  UNIQUE INDEX `song_name_UNIQUE` (`song_name` ASC),
  UNIQUE INDEX `song_filename_UNIQUE` (`song_filename` ASC),
  INDEX `fk_songs_authors_idx` (`song_author` ASC),
  INDEX `fk_songs_images1_idx` (`song_image_id` ASC),
  CONSTRAINT `fk_songs_authors`
    FOREIGN KEY (`song_author`)
    REFERENCES `mydb`.`authors` (`author_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_songs_images1`
    FOREIGN KEY (`song_image_id`)
    REFERENCES `mydb`.`images` (`image_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(64) NOT NULL,
  `user_password` VARCHAR(256) NOT NULL,
  `user_email` VARCHAR(96) NOT NULL,
  `user_permission` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC),
  UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permissions` (
  `permission_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `permission_name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`permission_id`),
  UNIQUE INDEX `permission_id_UNIQUE` (`permission_id` ASC),
  UNIQUE INDEX `permission_name_UNIQUE` (`permission_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_has_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_has_permissions` (
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `permission_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `permission_id`),
  INDEX `fk_users_has_permissions_permissions1_idx` (`permission_id` ASC),
  INDEX `fk_users_has_permissions_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_users_has_permissions_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_permissions_permissions1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `mydb`.`permissions` (`permission_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
